config/routes.rb
Teamsoccer::Application.routes.draw do

  resources :fields

  resources :contacts

  resources :referees

  resources :posts

  resources :players

  resources :games

  root :to => "pages#home"

  get "pages/home"
  get "pages/contact"
  get "pages/privacy"
  get "pages/terms"
  get "pages/faq"
  get "pages/about"

  resources :users do
    resource :teams
    resource :posts
  end
  resources :teams do 
    resource :players
    resource :posts
  end

  resources :sessions

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  has_many :team_assignments
  has_many :teams, :through => :team_assignments
  has_many :posts

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, :presence => true, :length => { :maximum => 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true, :format => { :with => VALID_EMAIL_REGEX }, :uniqueness => { :case_sensitive => false }
  validates :password, :length => { :minimum => 6 }
  validates :password_confirmation, :presence => true
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private

    def create_remember_token
      #self.remember_token = SecureRandom.urlsafe_base64
      self.remember_token = SecureRandom.base64
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @teams = @user.teams
    @posts = @user.posts

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, :notice => 'Welcome to Teamsoccer.org!' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name, :placeholder => "Name" %><br/>
    <%= f.text_field :email, :placeholder => "Email" %><br/>
    <%= f.password_field :password, :placeholder => "Password" %><br/>
    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
    <br />
    <%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create account</h1>
<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<blockquote>
  This will be the main view once logged on so have a block where you can see news and global posts/announcements. From the site,
  other users of the same team and maybe even other users of the whole site, if the post is hot or well-liked.
</blockquote>
<div class="row-fluid">
  <div class="span6">
    <%= render '/shared/teams' %>
    <%= render '/shared/posts' %>
  </div>
  <div class="span3 well">
    <h2><%= @user.name %></h2>
    <h3>Team Admin</h3>
    <table class="table">
      <tr><th>Email</th><td><%= @user.email %></td></tr>
    </table>
      <ul class="nav nav-list">
        <li><%= link_to raw('<i class="icon icon-plus-sign"></i> New Team'), new_team_path %></li>
        <li><%= link_to raw('<i class="icon icon-flag"></i> New Game'), new_game_path %></li>
        <li><%= link_to raw('<i class="icon icon-file"></i> New Post'), new_post_path %></li>
        <li><%= link_to raw('<i class="icon icon-user"></i> Edit Profile'), edit_user_path(@user) %></li>
        <li><%= link_to raw('<i class="icon icon-share"></i> Broadcast for a ref'), '#' %></li>
        <li><%= link_to raw('<i class="icon icon-envelope"></i> Email Team'), '#' %></li>
        <li><%= link_to raw('<i class="icon icon-share"></i> Add link'), '#' %></li>
        <li><%= link_to raw('<i class="icon icon-ok"></i> Todo list'), '#' %></li>
        <li><%= link_to raw('<i class="icon icon-user"></i> Referees'), referees_path %></li>
        <li><%= link_to raw('<i class="icon icon-map-marker"></i> Fields'), fields_path %></li>
      </ul>
  </div>
</div>