config/routes.rb
Teamsoccer::Application.routes.draw do

  resources :fields

  resources :contacts

  resources :referees

  resources :posts

  resources :players

  resources :games

  root :to => "pages#home"

  get "pages/home"
  get "pages/contact"
  get "pages/privacy"
  get "pages/terms"
  get "pages/faq"
  get "pages/about"

  resources :users do
    resource :teams
    resource :posts
  end
  resources :teams do 
    resource :players
    resource :posts
  end

  resources :sessions

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :hometeam, :class_name => "Team", :foreign_key => "hometeam_id"
  belongs_to :awayteam, :class_name => "Team", :foreign_key => "awayteam_id"
  belongs_to :field
  default_scope :order => 'games.gametime'

  def winner
    if homescore.to_i > awayscore.to_i
      hometeam
    elsif homescore.to_i < awayscore.to_i
      awayteam
    end
  end

  def loser
    if homescore.to_i < awayscore.to_i
      hometeam
    elsif homescore.to_i > awayscore.to_i
      awayteam
    end
  end

  def hometie
    if homescore?
      if homescore.to_i == awayscore.to_i
        hometeam
      end
    end
  end

  def awaytie
    if awayscore?
      if awayscore.to_i == homescore.to_i
        awayteam
      end
    end
  end

end
# == Schema Information
#
# Table name: games
#
#  id          :integer         not null, primary key
#  gametime    :datetime
#  hometeam_id :integer
#  awayteam_id :integer
#  notes       :text
#  field_id    :integer
#  fieldname   :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  homescore   :integer
#  awayscore   :integer
#

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, :notice => 'Game was successfully created.' }
        format.json { render :json => @game, :status => :created, :location => @game }
      else
        format.html { render :action => "new" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, :notice => 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game, :html => { :class => "" } ) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gametime %><br />
    <%= f.datetime_select :gametime %>
  </div>
  <div class="field">
    <%= f.label :hometeam_id %><br />
    <%= select("game", "hometeam_id", Team.all.collect {|th| [th.name, th.id ]} ) %>
  </div>
  <div class="field">
    <%= f.label :awayteam_id %><br />
    <%= select("game", "awayteam_id", Team.all.collect {|ta| [ta.name, ta.id ]} ) %>
  </div>
  <div>
    <%= f.text_field :homescore, :placeholder => "Home Score" %>
    <%= f.text_field :awayscore, :placeholder => "Away Score" %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :field_id %><br />
    <%= select("game", "field_id", Field.all.collect{|fld| [fld.name, fld.id ] } ) %>
    <%= link_to "New Field", new_field_path %>
  </div>
  <div class="field">
    <%= f.label :fieldname %><br />
    <%= f.text_field :fieldname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table class="table">
  <tr>
    <th>Gametime</th>
    <th>Hometeam</th>
    <th>Awayteam</th>
    <th>Notes</th>
    <th>Field</th>
    <th>Fieldname</th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= link_to game.gametime.strftime("%a %m/%d/%y %I:%M%p"), game %></td>
    <td><%= link_to game.hometeam.name, game.hometeam %></td>
    <td><%= link_to game.awayteam.name, game.awayteam %></td>
    <td><%= game.notes %></td>
    <td><%= game.field_id %></td>
    <td><%= game.fieldname %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<blockquote>
add refs to this game, add a button to send notification and it send a notification to team contacts and refs
about this game.  Checkbox for auto-notification reminder 3 days before the game.  People who got the email can click a link to confirm.  Put a link to enter the score.
</blockquote>

  <h2><%= @game.gametime.strftime("%a %m/%d/%y %I:%M%p") %></h2>

  <table class="table">
    <tr>
      <td><%= link_to @game.hometeam.name, @game.hometeam %> <strong><%= @game.homescore %></strong></td> 
      <td><%= link_to @game.awayteam.name, @game.awayteam %> <strong><%= @game.awayscore %></strong></td>
    </tr>
    <tr>
      <td colspan="2">
        <% if @game.field != nil %>
          <%= link_to @game.field.name, @game.field %> <%= @game.fieldname %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td colspan="2"><%= @game.notes %></td>
    </tr>
  </table>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>