config/routes.rb
Teamsoccer::Application.routes.draw do

  resources :fields

  resources :contacts

  resources :referees

  resources :posts

  resources :players

  resources :games

  root :to => "pages#home"

  get "pages/home"
  get "pages/contact"
  get "pages/privacy"
  get "pages/terms"
  get "pages/faq"
  get "pages/about"

  resources :users do
    resource :teams
    resource :posts
  end
  resources :teams do 
    resource :players
    resource :posts
  end

  resources :sessions

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/field.rb
class Field < ActiveRecord::Base
  has_many :games
  default_scope :order => 'fields.city'
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @fields }
    end
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
    @field = Field.find(params[:id])
    @games = @field.games

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @field }
    end
  end

  # GET /fields/new
  # GET /fields/new.json
  def new
    @field = Field.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @field }
    end
  end

  # GET /fields/1/edit
  def edit
    @field = Field.find(params[:id])
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(params[:field])

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, :notice => 'Field was successfully created.' }
        format.json { render :json => @field, :status => :created, :location => @field }
      else
        format.html { render :action => "new" }
        format.json { render :json => @field.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fields/1
  # PUT /fields/1.json
  def update
    @field = Field.find(params[:id])

    respond_to do |format|
      if @field.update_attributes(params[:field])
        format.html { redirect_to @field, :notice => 'Field was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @field.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field = Field.find(params[:id])
    @field.destroy

    respond_to do |format|
      format.html { redirect_to fields_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= form_for(@field) do |f| %>
  <% if @field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% @field.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :googlemap %><br />
    <%= f.text_area :googlemap %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing field</h1>

<%= render 'form' %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<h1>Listing fields</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th></th>
    <th></th>
  </tr>

<% @fields.each do |field| %>
  <tr>
    <td><%= link_to field.name, field %></td>
    <td><%= field.address %></td>
    <td><%= field.city %></td>
    <td><%= field.state %></td>
    <td><%= link_to 'Edit', edit_field_path(field) %></td>
    <td><%= link_to 'Destroy', field, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Field', new_field_path %>

app/views/fields/new.html.erb
<h1>New field</h1>

<%= render 'form' %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
  <h1><%= @field.name %></h1>
  <h3><%= @field.address %></h3>
  <h3><%= @field.city %> <%= @field.state %></h3>

<p>
  <%= raw(@field.googlemap) %>
</p>


<%= link_to 'Edit', edit_field_path(@field) %> | 
<%= link_to 'Back', fields_path %> | 
<%= link_to raw('<i class="icon icon-comment"></i> Post Comment'), '#' %>

<% if @field.games.any? %>
  <%= render '/shared/games' %>
<% end %>